# Generated by Django 5.0.2 on 2024-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "discount",
                    models.IntegerField(help_text="Percentage value (0 to 100)"),
                ),
                ("active", models.BooleanField()),
            ],
        ),
    ]
